### ISSUE TITLE
Should we propagate template plan errors to this provider 

### ISSUE THREAD

**Issue by stirby** [coder/terraform-provider-coderd#109]
A customer noticed that when the tf plan fails for a template, the coderd provider invoker fails without exposing the underlying template error. 

Does it make sense to raise the Template error to our coderd provider? Otherwise, they have to debug the template in a separate context.

Template Error:
<img width="591" alt="coder_ui_error" src="https://github.com/user-attachments/assets/a9fcb0b0-fe8b-4c0c-9353-5bb865b3e3ed">

What the coderd provider invoker shows:
<img width="995" alt="coderd_error" src="https://github.com/user-attachments/assets/4c90e048-b1ea-4a6f-9814-5a3ba5f4e251">

**Comment by ethanndickson** [comment]
The original intention was that users could stream logs from the provisioner by setting `TF_LOG` to `info`, but the UX there still kinda sucked. #95 now has the logs get dumped on error, which seems much better. It'll be in the release this week.

(I probably should've made a patch with it earlier, instead of holding off until the next Coder release)
